In [58]:
'''This problem was asked by Apple.

Suppose you have a multiplication table that is N by N. That is, a 2D array where the value at the i-th
row and j-th column is (i + 1) * (j + 1) (if 0-indexed) or i * j (if 1-indexed).

Given integers N and X, write a function that returns the number of times X appears as a value in an N by N multiplication table.

For example, given N = 6 and X = 12, you should return 4, since the multiplication table looks like this:

| 1 | 2 | 3 | 4 | 5 | 6 |

| 2 | 4 | 6 | 8 | 10 | 12 |

| 3 | 6 | 9 | 12 | 15 | 18 |

| 4 | 8 | 12 | 16 | 20 | 24 |

| 5 | 10 | 15 | 20 | 25 | 30 |

| 6 | 12 | 18 | 24 | 30 | 36 |

And there are 4 12's in the table'''



import numpy as np
import time


def foundInRow(tmpRow, v, tmpInd):
    retVal = 0;
    
    while (len(tmpRow) != 0):
        #print("Current row: ", tmpRow);
        middlePosition = (int)(len(tmpRow) / 2);
        #print("Current middle position: ", middlePosition);
        #print("Current middle element: ", tmpRow[middlePosition]);
        #print("Current type: ", type(tmpRow));ù
        #print(len(tmpRow));
        if (tmpRow[middlePosition] == v):
            retVal = 1;
            break;
        elif (v < tmpRow[middlePosition]):
            tmpRow = tmpRow[ : middlePosition]
        else:
            tmpRow = tmpRow[middlePosition + 1 : ]
    #if (retVal == 0):
    #    print("Value not found");
    #else:
    #    print("Value found");
    return retVal;
        
    #middlePosition = N / 2;
        #if matrix[i, middlePosition] == toBeFound:
        #    count += 1;
        #else:
            #generate new subarray
    
#####################################    

N = 7;
toBeFound = 12;

matrix = np.zeros((N, N))
for i in range(N):
    for j in range(N):
        matrix[i, j] = (i + 1) * (j + 1);
print("Input matrix: ");
print(matrix);

#(i + 1) * (j + 1)
count = 0;
startTime = time.clock();
for i in range(N):
    for j in range(N):
        if (matrix[i, j] == toBeFound):
            count += 1;
diffTime = time.clock() - startTime;
print("Value found ", count, " times. Time: ", diffTime,"\n\n");

count = 0;
startTime = time.clock();
for i in range(N):
    if (matrix[i, N - 1] >= toBeFound):
        returnValue = foundInRow(matrix[i].tolist(), toBeFound, i);
        count += returnValue;
diffTime = time.clock() - startTime;
print("Value found ", count, " times. Time: ", diffTime,"\n\n");
        #middlePosition = N / 2;
        #if matrix[i, middlePosition] == toBeFound:
        #    count += 1;
        #else:
            #generate new subarray

Input matrix: 
[[ 1.  2.  3.  4.  5.  6.  7.]
 [ 2.  4.  6.  8. 10. 12. 14.]
 [ 3.  6.  9. 12. 15. 18. 21.]
 [ 4.  8. 12. 16. 20. 24. 28.]
 [ 5. 10. 15. 20. 25. 30. 35.]
 [ 6. 12. 18. 24. 30. 36. 42.]
 [ 7. 14. 21. 28. 35. 42. 49.]]
Value found  4  times. Time:  0.0007289999994100071 


Value found  4  times. Time:  0.0008601999979873654 




C:\Users\sacinieri\Anaconda3\lib\site-packages\ipykernel_launcher.py:71: DeprecationWarning: time.clock has been deprecated in Python 3.3 and will be removed from Python 3.8: use time.perf_counter or time.process_time instead
C:\Users\sacinieri\Anaconda3\lib\site-packages\ipykernel_launcher.py:76: DeprecationWarning: time.clock has been deprecated in Python 3.3 and will be removed from Python 3.8: use time.perf_counter or time.process_time instead
C:\Users\sacinieri\Anaconda3\lib\site-packages\ipykernel_launcher.py:80: DeprecationWarning: time.clock has been deprecated in Python 3.3 and will be removed from Python 3.8: use time.perf_counter or time.process_time instead
C:\Users\sacinieri\Anaconda3\lib\site-packages\ipykernel_launcher.py:85: DeprecationWarning: time.clock has been deprecated in Python 3.3 and will be removed from Python 3.8: use time.perf_counter or time.process_time instead
